name: Get dir tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ls
      run: ls
    - name: Get dir tree
      run: curl -i https://api.github.com/repos/zhfanrui/test/contents
