name: Get dir tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get dir tree
        run: wget https://api.github.com/repos/$GITHUB_REPOSITORY/contents
      - name: git
        run: |
          remote_repo="https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" && \
          echo $remote_repo && \
          git init && \
          git config user.name "$GITHUB_ACTOR" && \
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && \
          git add . && \
          git commit -m 'get articles' && \
          git push --force $remote_repo master:tree && \
          rm -fr .git
