name: Get dir tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: get
        uses: zhfanrui/get-files-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
