name: Get dir tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: pwd
        run: pwd
      - name: touch
        run: touch 2
      - name: ls
        run: ls
#       - name: git
#         run: git
      - name: echo
        run: echo $GITHUB_REPOSITORY $HOME
#       - name: Get dir tree
#         run: curl -i https://api.github.com/repos/zhfanrui/test/contents
